# Generated by Django 3.2.9 on 2022-05-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sign_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='window',
            old_name='chat',
            new_name='sms',
        ),
        migrations.RemoveField(
            model_name='sign_in',
            name='surname',
        ),
    ]
