# Generated by Django 3.2.9 on 2022-05-22 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_name_sign_in_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign_in',
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
    ]
