# Generated by Django 3.2.9 on 2022-05-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220522_2144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sms',
            new_name='Question',
        ),
    ]
