# Generated by Django 3.2.9 on 2022-05-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_sms_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
    ]
